sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - pip install coveralls
script: coverage run --source=omnix setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: Utx9NIXKE4E1xIRUB8Cyk2smEBd0qgZYkm/BdFJs2pmfPHIUhY/MONiNm+VpUGEvtJ+MvT+Nv8hvw2TLyJlrMklfxbKDfzmiiHzKS1FDwl4KiowvvOlDy6Yc4kEf+Gwn6tnRs7Gdi+LngzbcH3LFnJ+KHNG0Vesdp204fZ4HyJY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
