dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.py2.txt
  - pip install -r extra.py2.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=omnix setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: Utx9NIXKE4E1xIRUB8Cyk2smEBd0qgZYkm/BdFJs2pmfPHIUhY/MONiNm+VpUGEvtJ+MvT+Nv8hvw2TLyJlrMklfxbKDfzmiiHzKS1FDwl4KiowvvOlDy6Yc4kEf+Gwn6tnRs7Gdi+LngzbcH3LFnJ+KHNG0Vesdp204fZ4HyJY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
